name: Checkstyle

on: [push, pull_request]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download Checkstyle
        run: |
          wget -q -O checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.21.1/checkstyle-10.21.1-all.jar

      - name: Run Checkstyle
        run: |
          java -jar checkstyle.jar -c /path/to/google_checks.xml -f xml src/*.java > checkstyle-result.xml
        continue-on-error: true

      - name: Annotate Pull Request
        if: failure()
        uses: docker://ghcr.io/staabm/annotate-pull-request-from-checkstyle
        with:
          report_files: checkstyle-result.xml

  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: |
          pylint sample.py
